# Generated by Django 4.1.3 on 2022-11-26 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menuallergy')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menucategory')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menu')),
            ],
        ),
    ]
