# Generated by Django 4.1.3 on 2022-11-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_listing_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
